### ISSUE TITLE
Radius of curves on corner modules

### ISSUE THREAD

**Issue by largo84** [Modurail/Publications#2]
The 4.1 standards indicate the radius center point for the main tracks 1 and 2 to be different. This allows for non-parallel tracks and prevents overlap. The current suggested doesn't show this.
- Should there be non-parallel tracks 1 and 2?
- Should the center point(s) show on the drawing?

**Comment by dbjherbert** [comment]
I can add the Centre Point.  Centre Point is decided based on the connector track (straight end leading to next module).  Previous Spec was 6" on Track 1 and 4.5" on Track 2 and 3.  New spec has the same connector track for the new Track Ends @ 3" each

**Comment by dbjherbert** [comment]
Drawing Updated
